export type VocabActionType = "SWITCH_TOPIC" | "UPLOAD_XLS_TABLE_REQUEST" | "UPLOAD_XLS_TABLE_RECEIVE" | "UPLOAD_XLS_TABLE_FAIL";
export type SentenceActionType = "NEXT_SENTENCE_REQUEST" | "NEXT_SENTENCE_RECEIVE" | "NEXT_SENTENCE_FAIL" | "CHANGE_INPUT_VALUE" | "MARK_INVALID_INPUTS"
export type HintActionType = "SET_HINTS" | "SHOW_HINT";
