export const SHOW_HINT = "SHOW_HINT";
export const SET_HINTS = "SET_HINTS";
export const SET_SENTENCE = "SET_SENTENCE";
export const UPLOAD_XLS_TABLE_REQUEST = "UPLOAD_XLS_TABLE_REQUEST";
export const UPLOAD_XLS_TABLE_RECEIVE = "UPLOAD_XLS_TABLE_RECEIVE";
export const SWITCH_TOPIC = "SWITCH_TOPIC";

export type VocabActionType = "SWITCH_TOPIC" | "UPLOAD_XLS_TABLE_REQUEST" | "UPLOAD_XLS_TABLE_RECEIVE" | "UPLOAD_XLS_TABLE_FAIL";
export type SentenceActionType = "NEXT_SENTENCE_REQUEST" | "NEXT_SENTENCE_RECEIVE" | "NEXT_SENTENCE_FAIL" | "CHANGE_INPUT_VALUE";
export type HintActionType = "SET_HINTS" | "SHOW_HINT";
