export const API_PATH = process.env.REACT_APP_API_PATH;
export const GOOGLE_SPREADSHEET_API = {
    DEVELOPER_KEY: process.env.REACT_APP_GOOGLE_SPREADSHEET_API.DEVELOPER_KEY,
    CLIENT_ID: process.env.REACT_APP_GOOGLE_SPREADSHEET_API.CLIENT_ID,
    APP_ID: process.env.REACT_APP_GOOGLE_SPREADSHEET_API.APP_ID
};
